# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


platform :ios do

 before_all do
    puts "Running before_all block"
    key_content = ENV['KEY_CONTENT']
    app_store_connect_api_key(key_id: "DUFSA785Q2",
                               issuer_id: "69a6de76-b502-47e3-e053-5b8c7c11a4d1",
                               key_content: key_content)
  end


  desc "Promote a TestFlight build to App Store and submit for review"
  lane :promote_to_app_store do

  # Set the desired version number
   version_number = ENV['VERSION_NUMBER']

    # Set the release notes
    release_notes = {
      'en-US' => ENV['RELEASE_NOTES']
    }
    build_number = ENV['BUILD_NUMBER']

    pwd = ENV['$FASTLANE_PASSWORD']


    puts "Try to deliver version: #{version_number} with build #{build_number}"
    puts "**********************pwd #{pwd}"

    # Ensure the metadata is up to date
    deliver(
      app_version: version_number,
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
      force: true
    )

    # Upload to App Store and submit for review
    upload_to_app_store(
      build_number: build_number,
      skip_metadata: true,
      skip_screenshots: true,
      skip_app_version_update: true,
      release_notes: release_notes,
      precheck_include_in_app_purchases: false,
      submit_for_review: true,
      automatic_release: true
    )
    puts "Version: #{version_number} with build #{build_number} has been deployed"

  end
    lane :latest_build_number do

        version_number = ENV['VERSION_NUMBER']
        release_notes = ENV['RELEASE_NOTES']

        puts "version_number: #{version_number}"
        puts "RELEASE_NOTES: #{release_notes}"
        puts "APP_STORE_CONNECT_API_KEY_PATH: #{ENV['APP_STORE_CONNECT_API_KEY_PATH']}"
        puts "APP_STORE_CONNECT_ISSUER_ID: #{ENV['APP_STORE_CONNECT_ISSUER_ID']}"
        puts "APP_STORE_CONNECT_KEY_ID: #{ENV['APP_STORE_CONNECT_KEY_ID']}"#

      # Fetch the latest build from TestFlight
      latest_build_number = latest_testflight_build_number(
        app_identifier: "com.threedeers.myCloudApp.myNewCloudProject"
      )

      # Print the latest build number
      puts "Latest TestFlight Build Number: #{latest_build_number}"

    end

    platform :ios do
     desc "Load ASC API Key information to use in subsequent lanes"
     lane :load_asc_api_key do
       app_store_connect_api_key(
         key_id: ENV["ASC_KEY_ID"],
         issuer_id: ENV["ASC_ISSUER_ID"],
         key_content: ENV["ASC_KEY"],
         is_key_content_base64: true,
         in_house: false # detecting this via ASC private key not currently supported
       )
     end
    end


end
