# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Promote a TestFlight build to App Store and submit for review"
  lane :promote_to_app_store do

  # Set the desired version number
   version_number = ENV['VERSION_NUMBER']

    # Set the release notes
    release_notes = {
      'en-US' => ENV['RELEASE_NOTES']
    }
    build_number = ENV['BUILD_NUMBER']


    # Fetch the latest build from TestFlight
#     latest_build_number = latest_testflight_build_number(
#       app_identifier: "com.threedeers.myCloudApp.myNewCloudProject"
#     )

    puts "Try to deliver version: #{version_number} with build #{build_number}"

    # Ensure the metadata is up to date
    deliver(
      app_version: version_number,
      skip_metadata: true,
      skip_screenshots: true,
      force: true
    )

    # Upload to App Store and submit for review
    upload_to_app_store(
      build_number: build_number,
      skip_metadata: true,
      skip_screenshots: true,
      skip_app_version_update: true,
      release_notes: release_notes,
      submit_for_review: true,
      automatic_release: false
    )
    puts "Version: #{version_number} with build #{build_number} has been deployed"

  end
    lane :latest_build_number do

      # Fetch the latest build from TestFlight
      latest_build_number = latest_testflight_build_number(
        app_identifier: "com.threedeers.myCloudApp.myNewCloudProject"
      )

      # Print the latest build number
      puts "Latest TestFlight Build Number: #{latest_build_number}"

    end
end
